### PR TITLE
Enhanced Ui

### PR DESCRIPTION
**Pull request by ahamedibrahim2002**
## Related Issue 

- Information about the related issue

Closes: # 

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |
 
## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/web3community/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by ahamedibrahim2002** [comment]
Updated
      1)updated gradle to latest version
      2)updated ui
      3)implement delete all button in home page
      4)cleared some minor

**Review by unnikrishnan2002 — CHANGES_REQUESTED** [review]
Hey please remove the commits of  `.idea` directory file . That is the `.idea/.name` , `idea/gradle.xml` and `.ide/misc.xml` files

**Comment by ahamedibrahim2002** [comment]
done

**Review by unnikrishnan2002 — APPROVED** [review]

**Comment by unnikrishnan2002** [comment]
Thanks for the contribution 😄

**Pull request merged**
